config update

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,25 +1,6 @@
 version: 2.1
 
 commands:
-  install_awscli:
-    description: Install AWS cli
-    steps:
-      - run:
-          name: Install AWS cli
-          command: |
-            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            sudo ./aws/install
-
-  install_nodejs:
-     description: Install Node.js 13
-     steps:
-      - run:
-          name: Install Node.js 13
-          command: |
-            curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
-            sudo apt install -y nodejs
-
 
   install_ansible:
     description: Install Ansible
@@ -35,11 +16,10 @@ commands:
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
-      # Add parameter here   
+      # Add parameter here
       workflow_id:
         default: "${CIRCLE_WORKFLOW_ID:0:7}"
-        type: string
-
+        type: string   
     steps:
       - run:
           name: Destroy environments
@@ -50,16 +30,14 @@ commands:
             aws cloudformation delete-stack --stack-name "udapeople-backend-<<parameters.workflow_id>>"
             aws cloudformation delete-stack --stack-name "udapeople-frontend-<<parameters.workflow_id>>"
             
-            
 
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
-      # Add parameter here 
+      # Add parameter here
       workflow_id:
         default: "${CIRCLE_WORKFLOW_ID:0:7}"
-        type: string
-    
+        type: string     
     steps:
       - run:
           name: Revert migrations
@@ -72,9 +50,7 @@ commands:
               cd ~/project/backend
               npm install
               npm run migrations:revert
-            fi
-
-            
+            fi            
 jobs:
   build-frontend:
     docker:
@@ -104,10 +80,10 @@ jobs:
       - run:
           name: Back-end build
           command: |
-            # Your code here
-            cd backend
-            npm install
-            npm run build
+             # Your code here
+             cd backend
+             npm install
+             npm run build
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
@@ -120,22 +96,18 @@ jobs:
       # Checkout code from git
       - checkout
       # Restore from cache
-      
       - restore_cache:
           keys: [frontend-test]
       # Your job code here
       - run:
-          name: Frontend test
+          name: front-end test
           command: |
-            # Your code here
             cd frontend
             npm install
             npm run test
       - save_cache:
           paths: [frontend/node_modules]
-          key: frontend-test
-      
-                
+          key: front-end test            
   test-backend:
     docker:
       # Docker image here
@@ -144,21 +116,19 @@ jobs:
       # Checkout code from git
       - checkout
       # Restore from cache
-      
       - restore_cache:
           keys: [backend-test]
       # Your job code here
       - run:
-          name: Backend test
+          name: Back-end test
           command: |
-            # Your code here
-            cd backend
-            npm install
-            npm run test
+             # Your code here
+             cd backend
+             npm install
+             npm run test
       - save_cache:
           paths: [backend/node_modules]
-          key: backend-test
-            
+          key: backend-test      
   scan-frontend:
     docker:
       # Docker image here
@@ -167,60 +137,59 @@ jobs:
       # Checkout code from git
       - checkout
       # Restore from cache
-      
       - restore_cache:
-          keys: [scanfrontend-test]
+          keys: [scanningfrontend]
       # Your job code here
       - run:
-          name: Scan-Frontend
+          name: Frontend Scan
           command: |
-            # Your code here
-            cd frontend
-            npm install
-            # npm install oauth-sign@^0.9.0
-            npm audit fix --audit-level=critical --force
-            npm audit --audit-level=critical
+             # Your code here
+             cd frontend
+             npm install
+             # npm install oauth-sign@^0.9.0
+             npm audit fix --audit-level=critical --force
+             npm audit fix --audit-level=critical --force
+             npm audit --audit-level=critical
       - save_cache:
           paths: [frontend/node_modules]
-          key: scanfrontend-test
+          key: scanningfrontend
 
   scan-backend:
     docker:
-        # Docker image here
+      # Docker image here
       - image: circleci/node:13.8.0
     steps:
       # Checkout code from git
       - checkout
       # Restore from cache
-      
       - restore_cache:
-          keys: [scanbackend-test]
+          keys: [scanningbackend]
       # Your job code here
       - run:
-          name: Scan-Backend
+          name: Backend Scan
           command: |
-            # Your code here
-            cd backend
-            npm install
-            # npm install oauth-sign@^0.9.0
-            npm audit fix --audit-level=critical --force
-            npm audit fix --audit-level=critical --force
-            npm audit --audit-level=critical
+             # Your code here
+             cd backend
+             npm install
+             # npm install oauth-sign@^0.9.0
+             npm audit fix --audit-level=critical --force
+             npm audit fix --audit-level=critical --force
+             npm audit --audit-level=critical
       - save_cache:
           paths: [backend/node_modules]
-          key: scanbackend-test
+          key: scanningbackend
 
   deploy-infrastructure:
     docker:
       # Docker image here that supports AWS CLI
-     - image: amazon/aws-cli
+      - image: amazon/aws-cli
     steps:
       # Checkout code from git
       - checkout
       - run:
           name: Install dependencies
           command: |
-            yum install -y tar gzip
+              yum install -y tar gzip
 
       - run:
           name: Ensure back-end infrastructure exists
@@ -230,9 +199,8 @@ jobs:
               --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
               --tags project=udapeople
+
             
-               
-             
       - run:
           name: Ensure front-end infrastructure exist
           command: |
@@ -241,12 +209,10 @@ jobs:
               --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
               --tags project=udapeople
-              
-              
+
       - run:
           name: Add back-end ip to ansible inventory
           command: |
-          
             # Your code here
             cd .circleci/ansible
             cat inventory.txt
@@ -260,7 +226,7 @@ jobs:
             # --output text 
             # )
             # echo ${BACKEND_IP}
-
+            
       - persist_to_workspace:
           root: ~/
           paths:
@@ -272,222 +238,158 @@ jobs:
       # Docker image here that supports Ansible
       - image: cimg/base:stable
     steps:
+      # Checkout code from git
       - checkout
       - add_ssh_keys:
-          fingerprints:
-            - "a4:9d:96:eb:ac:e1:aa:05:fb:97:f2:1d:e8:2c:0e:9c"
+          fingerprints: 
+            - "f4:0c:64:c1:d7:9d:05:e4:14:63:1e:05:fd:26:d6:5f"
+      # Add ssh keys with fingerprint
       - attach_workspace:
           at: ~/
-    
-      - install_ansible    
-      - install_awscli
+          
+      - install_ansible
+      # attach workspace
       - run:
           name: Configure server
           command: |
             cd .circleci/ansible
             cat inventory.txt
-
             ansible-playbook -i inventory.txt configure-server.yml
       - destroy-environment
+      - run:
+          name: Install dependencies
+          command: |
+            # Your code here
+            exit 1
+      - run:
+          name: Configure server
+          command: |
+            # Your code here
+            exit 1
+      # Here's where you will add some code to rollback on failure      
 
   run-migrations:
     docker:
       # Docker image here that supports NodeJS
       - image: circleci/node:13.8.0
     steps:
+      # Checkout code from git
       - checkout
       - run:
           name: Run migrations
           command: |
+            # Your code here
             cd backend
             npm install
             npm run migrations > migrations_dump.txt
       - run:
-          name: Send migration results to kvdb
+          name: Send migration results to memstash
           command: |
+            # Your code here
             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
             then
-             curl --insecure https://kvdb.io/33GxcCpH7rHocPuWALvF32/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
-            fi
-      - destroy-environment 
-      - revert-migrations
-  
-  deploy-frontend:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-
-      - add_ssh_keys:
-          fingerprints: 
-            - "a4:9d:96:eb:ac:e1:aa:05:fb:97:f2:1d:e8:2c:0e:9c"
-      - attach_workspace:
-          at: ~/
-
-      - install_nodejs
-      - install_awscli
-      - install_ansible
-      - run:
-          name: Get backend url
-          command: |
-            # your code here
-            export BACKEND_IP=$(aws ec2 describe-instances \
-            --query 'Reservations[*].Instances[*].PublicIpAddress' \
-            --filter Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} \
-            --output text 
-            )
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo "API_URL = ${API_URL}"
-            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
-            cat frontend/.env
-      - run:
-          name: Deploy frontend objects
-          command: |
-            cd frontend
-            sudo npm install -g npm@latest
-            rm -rf node_modules
-            npm install
-            npm run build
-            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+              curl --insecure https://kvdb.io/33GxcCpH7rHocPuWALvF32/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+            fi  
+     # Here's where you will add some code to rollback on failure      
       - destroy-environment
       - revert-migrations
 
-     
+#   deploy-frontend:
+#     docker:
+#       # Docker image here that supports AWS CLI
+#     steps:
+#       # Checkout code from git
+#       - run:
+#           name: Install dependencies
+#           command: |
+#             # your code here
+#       - run:
+#           name: Get backend url
+#           command: |
+#             # your code here
+#             export API_URL="http://${BACKEND_IP}:3030"
+#             echo "${API_URL}"
+#       - run:
+#           name: Deploy frontend objects
+#           command: |
+#             # your code here
+#       # Here's where you will add some code to rollback on failure      
                     
-  deploy-backend:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      # Add ssh keys with fingerprint
-      # attach workspace
-      - checkout
-      - add_ssh_keys:
-          fingerprints: 
-            - "f4:0c:64:c1:d7:9d:05:e4:14:63:1e:05:fd:26:d6:5"
-      - attach_workspace:
-          at: ~/
-      - install_nodejs
-      - install_awscli
-      - install_ansible
-      - run:
-          name: Deploy backend
-          command: |
-            cd backend
+#   deploy-backend:
+#     docker:
+#       # Docker image here that supports Ansible
+#     steps:
+#       # Checkout code from git
+#       # Add ssh keys with fingerprint
+#       # attach workspace
+#       - run:
+#           name: Install dependencies
+#           command: |
+#             # your code here
+#       - run:
+#           name: Deploy backend
+#           command: |
+#             # your code here
+#       # Here's where you will add some code to rollback on failure  
 
-            npm i
-            npm run build
-            cd ..
+#   smoke-test:
+#     docker:
+#       # Lightweight Docker image 
+#     steps:
+#       # Checkout code from git
+#       - run:
+#           name: Install dependencies
+#           command: |
+#             # your code here
+#       - run:
+#           name: Get backend url
+#           command: |
+#             # your code here
+#       - run:
+#           name: Backend smoke test.
+#           command: |
+#             # your code here
+#       - run:
+#           name: Frontend smoke test.
+#           command: |
+#             # your code here
+#       # Here's where you will add some code to rollback on failure  
 
-            cd .circleci/ansible
-            mkdir files
-            cd files
-            tar -C ../../../backend -czvf artifact.tar.gz .
-            cd ../
+#   cloudfront-update:
+#     docker:
+#       # Docker image here that supports AWS CLI
+#     steps:
+#       # Checkout code from git
+#       - run:
+#           name: Install dependencies
+#           command: |
+#             # your code here
+#       - run:
+#           name: Update cloudfront distribution
+#           command: |
+#             # your code here
+#       # Here's where you will add some code to rollback on failure  
+
+# cleanup:
+#     docker:
+#       # Docker image here
+#     steps:
+#       # Checkout code from git
+#       - run:
+#           name: Get old stack workflow id
+#           command: |
+#             # your code here
+#             export OldWorkflowID="the id here"
+#             export STACKS=[] #put the list of stacks here
+#       - run:
+#           name: Remove old stacks and files
+#           command: |
+#             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+#             then
+#               # your code here
+#             fi
             
-            echo "Contents  of the inventory.txt file is -------"
-            cat inventory.txt
-            ansible-playbook -i inventory.txt deploy-backend.yml
 
-
-      - destroy-environment
-      - revert-migrations
-
-
-  smoke-test:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-     
-      - install_nodejs
-      - install_awscli
-      - run:
-          name: Backend smoke test.
-          command: |
-              BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-                --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-                --query 'Reservations[*].Instances[*].PublicIpAddress' \
-                --output text)
-              export API_URL=http://${BACKEND_PUBLIC_IP}:3030
-              echo ${BACKEND_PUBLIC_IP}
-              echo backend-${CIRCLE_WORKFLOW_ID:0:7}
-              echo ${API_URL}
-              if curl -s $API_URL/api/status | grep "ok"
-              then
-                exit 0
-              else
-                exit 1
-              fi
-      - run:
-          name: Frontend smoke test.
-          command: |
-              FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
-              echo $FRONTEND_WEBSITE
-              if curl -s $FRONTEND_WEBSITE | grep "Welcome"
-              then
-                exit 0
-              else
-                exit 1
-              fi
-      - destroy-environment
-      - revert-migrations
-
-
- 
-
-  cloudfront-update:
-    docker:
-      - image: amazon/aws-cli
-    steps:
-      - checkout
-      - run:
-          name: Install dep / Save Old Workflow ID to kvdb.io
-          command: |
-            export OLD_WORKFLOW_ID=$(aws cloudformation \
-            list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-            --no-paginate --output text)
-            echo "Old Wokflow ID: $OLD_WORKFLOW_ID"
-            curl https://kvdb.io/33GxcCpH7rHocPuWALvF32/old_workflow_id -d "${OLD_WORKFLOW_ID}"
-      - run:
-          name: Update cloudfront distribution
-          command: |
-            aws cloudformation deploy \
-            --template-file .circleci/files/cloudfront.yml \
-            --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
-            --stack-name InitialStack
-      - destroy-environment
-      - revert-migrations
- 
-
-  cleanup:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - install_awscli
-      - run:
-          name: Get old stack workflow id
-          command: |
-            export STACKS=($(aws cloudformation list-stacks \
-                --query "StackSummaries[*].StackName" \
-                --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
-            echo Stack names: "${STACKS[@]}"
-            export OldWorkflowID=$(curl --insecure https://kvdb.io/33GxcCpH7rHocPuWALvF32/old_workflow_id)
-            echo Old Workflow ID: $OldWorkflowID
-      - run:
-          name: Remove old stacks and files
-          command: |
-            export OldWorkflowID=$(curl --insecure https://kvdb.io/33GxcCpH7rHocPuWALvF32/old_workflow_id)
-            echo Old Workflow ID: $OldWorkflowID 
-
-            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-            then
-              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
-              aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
-              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
-            fi
-
-        
 workflows:
   default:
     jobs:
@@ -508,8 +410,8 @@ workflows:
               only: [master]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
-      # - run-migrations:
-      #     requires: [configure-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
       # - deploy-frontend:
       #     requires: [run-migrations]
       # - deploy-backend:
